[tools]
atlas = "0.32.0"
go = "1.23.2"
golangci-lint = "2.0.2"
gotestsum = "1.12.0"
node = "20.19.0"
protoc = "29.3"
protoc-gen-go = "1.36.6"
protoc-gen-go-grpc = "1.5.1"
protoc-gen-validate = "1.2.1"
rust = "1.85.0"

[env]
MISE_NODE_COREPACK = true

[tasks]
build-to-minikube = { dir = "{{config_root}}", run = 'scripts/build-to-minikube.sh' }
run-minikube = { dir = "{{config_root}}", run = 'scripts/local-test.sh' }
spark-cli = { dir = "{{config_root}}/sdks/js", run = 'yarn install && yarn build && cd examples/spark-cli && yarn build && yarn run cli' }
spark-cli-prod = { dir = "{{config_root}}/sdks/js", run = 'yarn install && yarn build && cd examples/spark-cli && yarn build && yarn run cli:prod' }
test-go = { dir = "{{config_root}}/spark", run = 'mise test' }
test-grpc = { dir = "{{config_root}}/spark", run = 'mise test-grpc' }
test-js = { dir = "{{config_root}}/sdks/js", run = 'yarn install && yarn test' }
test-js-integration = { dir = "{{config_root}}/sdks/js", run = 'yarn install && yarn test:integration' }

[settings]
activate_aggressive = true
disable_backends = ["asdf"]
