bitcoind:
  regtest:
    network: regtest
    host: 127.0.0.1:8332
    rpcuser: testutil
    rpcpassword: testutilpassword
    zmqpubrawblock: tcp://127.0.0.1:28332
lrc20:
  regtest:
    disablerpcs: false
    disablel1: false
    network: regtest
    host: 127.0.0.1:18530
    withdrawbondsats: 1000000 # 0.01 BTC
    withdrawrelativeblocklocktime: 1000
    grpcpagesize: 200
    grpcpoolsize: 10
